<a href="https://colab.research.google.com/github/aliaa-13/Data-analytics-using-python-/blob/main/Day21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy
import numpy as np
print("Numpy Version",np.__version__)
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)
print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape )
print("data type",arr2.dtype)
print("Number of dimensions:",arr2.ndim)
print("Size of arr1:", arr1.size)
print("Size of arr2:", arr2.size)
zeros=np.zeros((2,3))
ones=np.ones((3,2))
identity=np.eye(3)
random=np.random.rand(2,2)
print("Zeros:\n",zeros)
print("Ones:\n",ones)
print("Identity:\n",identity)
print("Random:\n",random)
arr_range=np.arange(0,10,2)
print("arr_range:",arr_range)
arr_linspace=np.linspace(0,1,5)
print("arr_linspace:",arr_linspace)

Numpy Version 2.0.2
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Shape of arr1: (5,)
Shape of arr2: (2, 3)
data type int64
Number of dimensions: 2
Size of arr1: 5
Size of arr2: 6
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random:
 [[3.26764600e-04 6.25943128e-01]
 [6.53271089e-01 3.96842556e-01]]
arr_range: [0 2 4 6 8]
arr_linspace: [0.   0.25 0.5  0.75 1.  ]
